spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 0000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  web:
    resources:
      add-mappings: true


logging:
  level:
    root: warn
    com.ys: info
  file:
    name: log/blog-pro.log

server:
  port: 8081
